name: coolapk_flutter
description: Coolapk Flutter version.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  crypto: ^2.1.3
  uuid: ^2.0.4
  path_provider: ^1.6.0
  path_provider_fde:
    path: ./path_provider_fde
  carousel_slider: ^1.4.1
  flutter_html: ^0.11.1
  qr_flutter: ^3.2.0
  flutter_speed_dial: ^1.2.5
  # extended_image: ^0.7.2 // some bug
  extended_image:
    git:
      url: git://github.com/jonataslaw/extended_image.git
  sticky_headers: ^0.1.8
  flutter_rating_bar: ^3.0.1
  waterfall_flow: ^0.1.3
  solid_bottom_sheet: ^0.1.9
  flutter_easyrefresh: ^2.0.9
  toast: ^0.1.5
  dartx: ^0.3.0
  # fluro: ^1.5.2 # Flutter SDK version >=1.5.0 <1.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Sarasa-UI-SC-Regular
      fonts:
        # - asset: assets/fonts/sarasa-ui-sc-light.ttf
        #   weight: 200
        - asset: assets/fonts/sarasa-ui-sc-regular.ttf
        # - asset: assets/fonts/sarasa-ui-sc-bold.ttf
        #   weight: 600
  assets:
    - assets/images/
    - assets/images/emoji/
